Merge branch 'kohler/master' from GitHub 07441a4

diff --git a/click-buildtool.in b/click-buildtool.in
--- a/click-buildtool.in
+++ b/click-buildtool.in
@@ -8,7 +8,7 @@
 # Copyright (c) 2001-2003 International Computer Science Institute
 # Copyright (c) 2008 Meraki, Inc.
 # Copyright (c) 2004-2011 Regents of the University of California
-# Copyright (c) 2000-2013 Eddie Kohler
+# Copyright (c) 2000-2014 Eddie Kohler
 #
 # Permission is hereby granted, free of charge, to any person obtaining a
 # copy of this software and associated documentation files (the "Software"),
@@ -84,7 +84,7 @@ Options:
   -n, --length=N           Set maximum symbol length to N.
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -192,7 +192,7 @@ Usage: click-buildtool compile-shortensyms [BUILD COMMAND]
 Options:
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -351,7 +351,7 @@ Options:
       --checksum FILE        Write checksum data to FILE.
   -h, --help                 Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -775,7 +775,7 @@ Options:
   -V, --verbose            Print more information.
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -962,7 +962,7 @@ Options:
   -V, --verbose            Print more information.
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     -*)
@@ -1088,10 +1088,35 @@ provides_usage () {
     exit 1
 }
 
+default_elementmap_provisions () {
+    e=
+    oldprefix="$clickbuild_prefix"
+    path="$CLICKPATH"
+    while [ -z "$e" ]; do
+        clickbuild_prefix="`echo "$path" | sed 's/^\([^:]*\).*$/\1/'`"
+        path="`echo "$path" | sed 's/^[^:]*:*//'`"
+        if [ -n "$clickbuild_prefix" -a -f "@clickbuild_clickdatadir@/elementmap.xml" ]; then
+            e="@clickbuild_clickdatadir@/elementmap.xml"
+        elif [ -n "$clickbuild_prefix" -a -f "$clickbuild_prefix/elementmap.xml" ]; then
+            e="$clickbuild_prefix/elementmap.xml"
+        elif [ -z "$clickbuild_prefix" -a -f "${clickbuild_clickdatadir}/elementmap.xml" ]; then
+            e="$clickbuild_clickdatadir/elementmap.xml"
+        fi
+        if test -z "$path"; then break; fi
+    done
+    clickbuild_prefix="$oldprefix"
+
+    if [ -n "$e" ]; then
+        elementmap_provisions "$e"
+    else
+        echo "click-buildtool: can't find default elementmap" 1>&2
+    fi
+}
+
 provides () {
     provisions="$default_provisions
 $driver_provisions
-"`elementmap_provisions ${clickbuild_clickdatadir}/elementmap.xml`
+"`default_elementmap_provisions`
     requirements=""
     stdin=n; query=n; print=n
     while [ x"$1" != x ]; do
@@ -1136,7 +1161,7 @@ Options:
   -l, --print              Print 0 (REQs not provided) or 1 (REQs provided).
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     -)
@@ -1187,7 +1212,7 @@ Usage: ld ... 2>&1 | click-buildtool quietlink
 Options:
   -h, --help                 Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -1241,7 +1266,7 @@ Usage: click-buildtool prefix
 Options:
   -h, --help                 Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -1281,7 +1306,7 @@ Options:
                            no license).
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -1329,7 +1354,7 @@ Usage: click-buildtool kbuild > Kbuild
 Options:
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -1401,7 +1426,7 @@ Options:
   -h, --help               Print this message and exit.
   -[other options]         Passed to the C/C++ compiler.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     -*)
@@ -1434,7 +1459,7 @@ $1"; shift 1
 	echo "Unknown driver $driver" 1>&2
 	exit 1
     fi
-    if test -n "$L"; then osuffix=".$L.o"; else osuffix=".o"; fi
+    if test -n "$L"; then osuffix=".${L}o"; else osuffix=".o"; fi
 
     if test -n "$dir"; then cd "$dir"; fi
     echo > ${pkg}-${L}elem.conf
@@ -1507,7 +1532,7 @@ Options:
   -C, --directory DIR      Switch to DIR directory before running.
   -h, --help               Print this message and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
 	exit 0;;
     *)
@@ -1567,11 +1592,7 @@ case $1 in
   --vers|--versi|--versio|--version)
      cat <<'EOF'
 click-buildtool (Click) @CLICK_VERSION@
-Copyright (c) 2000-2001 Massachusetts Institute of Technology
-Copyright (c) 2000-2004 Mazu Networks, Inc.
-Copyright (c) 2001-2003 International Computer Science Institute
-Copyright (c) 2004-2007 Regents of the University of California
-Copyright (c) 2000-2012 Eddie Kohler
+Copyright (c) 2000-2014 Eddie Kohler and others
 This is free software; see the source for copying conditions.
 There is NO warranty, not even for merchantability or fitness for a
 particular purpose.
@@ -1612,7 +1633,7 @@ Options:
   -C, --clickprefix PFX    Set the prefix for locating data files.
       --version            Print version number and exit.
 
-Report bugs to <click@pdos.lcs.mit.edu>.
+Report bugs to <click@librelist.com>.
 EOF
      exit 0;;
   findelem)
